# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    backup.ssh.configuration:
        class: Ssh\Configuration
        arguments: [%backup.ssh.host%]

    backup.ssh.authentication:
        class: Ssh\Authentication\Password
        arguments: [%backup.ssh.username%, %backup.ssh.password%]
    backup.ssh.session:
        class: Ssh\Session
        arguments: [@backup.ssh.configuration, @backup.ssh.authentication]

    backup.sftp:
        class: Ssh\Sftp
        arguments: [@backup.ssh.session]
